// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `console_log_level`, `core_error_json`, `core_error_kind`, `decode_key`, `error_json`, `from_json`, `manager`, `ok_json`, `parse_network_opt`, `parse_network`, `parse_variant`, `refuse_oversized_nested_ur`, `refuse_oversized_ur`, `to_json`

/// Opens (or creates) the vault under `data_dir` with a 32-byte key given
/// as 64 hex characters. Idempotent: once initialized, later calls (hot
/// restarts) succeed without reopening.
///
/// The screens, the periodic task and the live watch each run in an
/// isolate of their own, in this one process, and each calls this when
/// it starts: two of them can call it at once. The vault takes one
/// opener at a time, within a process as between two, so a second open
/// would fail with `vault_in_use` instead of finding the first. One
/// call opens, and any other waits for it and shares its manager.
Future<String> initManager({required String dataDir, required String keyHex}) =>
    RustLib.instance.api.crateApiInitManager(dataDir: dataDir, keyHex: keyHex);

/// The key to store and open a new vault with, as 64 hex characters,
/// for a first launch: no vault yet, and no key kept for one.
///
/// The screens, the periodic task and the live watch each start in an
/// isolate of their own, and on a first launch each of them finds no
/// vault and no key. Were each to draw its own, the vault would be
/// sealed under the first key to reach [`init_manager`] while the
/// storage kept whichever was written last, and the next launch could
/// not open it. Drawn here, in one cell for the process, every caller
/// gets the same key: they all store that one and open with it.
Future<String> freshVaultKey() => RustLib.instance.api.crateApiFreshVaultKey();

/// Classifies pasted or scanned wallet material. Returns the serialized
/// `ParsedInput` to pass back to [`add_wallet`] after user confirmation.
/// `script` is the user's script type choice for a lone extended key
/// (`legacy`, `nested_segwit`, `segwit`, `taproot`), ignored otherwise.
Future<String> parseInput({required String input, String? script}) =>
    RustLib.instance.api.crateApiParseInput(input: input, script: script);

/// Classifies wallet material with the choices of the import screen:
/// `options_json` is a serialized `ImportOptions` (script type,
/// derivation paths, and the network the wallet goes to), all
/// optional. Everything the input fixes by itself ignores the first
/// two; the network decides the first address shown.
Future<String> parseInputWithOptions({
  required String input,
  required String optionsJson,
}) => RustLib.instance.api.crateApiParseInputWithOptions(
  input: input,
  optionsJson: optionsJson,
);

/// Reads a server address scanned or pasted into the backend settings:
/// the Electrum one-liner `host:port:s|t` that node dashboards print,
/// an `ssl://`/`tcp://` address, or an `http(s)://` Esplora endpoint.
/// Returns the serialized `ScannedBackend`; the screen fills its fields
/// with it and the person still presses Save.
Future<String> parseBackend({required String input}) =>
    RustLib.instance.api.crateApiParseBackend(input: input);

/// Assembles the QR frames scanned so far (plain text, UR, BBQr) from a
/// JSON array of strings. Returns the serialized `QrProgress`: feed the
/// growing list until `complete` is true, then pass `text` to
/// [`parse_input`].
Future<String> assembleQr({required String framesJson}) =>
    RustLib.instance.api.crateApiAssembleQr(framesJson: framesJson);

/// Adds a wallet from a `ParsedInput` JSON on an explicit network.
/// Returns the new wallet's metadata.
Future<String> addWallet({
  required String name,
  required String parsedJson,
  required String network,
}) => RustLib.instance.api.crateApiAddWallet(
  name: name,
  parsedJson: parsedJson,
  network: network,
);

/// Lists wallet metadata, optionally restricted to one network.
Future<String> listWallets({String? network}) =>
    RustLib.instance.api.crateApiListWallets(network: network);

/// Removes a wallet from this device.
Future<String> removeWallet({required String id}) =>
    RustLib.instance.api.crateApiRemoveWallet(id: id);

Future<String> renameWallet({required String id, required String name}) =>
    RustLib.instance.api.crateApiRenameWallet(id: id, name: name);

/// Changes the glyph a wallet shows next to its name. `icon` is one of
/// the serde names: `wallet`, `key`, `shield`, `map_pin`, `snowflake`,
/// `landmark`, `piggy_bank`.
Future<String> setWalletIcon({required String id, required String icon}) =>
    RustLib.instance.api.crateApiSetWalletIcon(id: id, icon: icon);

/// Puts a wallet ahead of the others in the live watch, or back among
/// them. When the watch cannot follow every address, the pinned wallets
/// are followed first. Kept in the vault; the watch takes the new order
/// by itself.
Future<String> setWalletLivePinned({
  required String id,
  required bool pinned,
}) => RustLib.instance.api.crateApiSetWalletLivePinned(id: id, pinned: pinned);

/// Puts the listed wallets in that order. Wallets left out keep their
/// slots, so the list of one network reorders without moving another
/// network's wallets. A repeated id is refused, an unknown one too.
Future<String> reorderWallets({required List<String> ids}) =>
    RustLib.instance.api.crateApiReorderWallets(ids: ids);

Future<String> walletSnapshot({required String id}) =>
    RustLib.instance.api.crateApiWalletSnapshot(id: id);

/// The wallet's descriptor read as a spending policy: its keys, its
/// branches, and every timelock evaluated against the chain tip and the
/// wallet's coins. Returns a serialized `PolicySnapshot`; a watched
/// address yields one with no keys and no branches.
Future<String> walletPolicy({required String id}) =>
    RustLib.instance.api.crateApiWalletPolicy(id: id);

Future<String> txDetail({required String id, required String txid}) =>
    RustLib.instance.api.crateApiTxDetail(id: id, txid: txid);

Future<String> utxos({required String id}) =>
    RustLib.instance.api.crateApiUtxos(id: id);

/// The next unused receive address plus `lookahead` upcoming ones.
Future<String> receiveAddresses({required String id, required int lookahead}) =>
    RustLib.instance.api.crateApiReceiveAddresses(id: id, lookahead: lookahead);

/// Revealed addresses of a wallet, by keychain, with usage and balance.
/// Capped by the core: an audit view, not an infinite scroll.
Future<String> addressList({required String id}) =>
    RustLib.instance.api.crateApiAddressList(id: id);

/// Builds a CSV export of one wallet's transactions from serialized
/// `ExportOptions`. Returns `{"ok": ExportResult}`; nothing leaves the
/// device.
Future<String> exportTransactions({
  required String id,
  required String optionsJson,
}) => RustLib.instance.api.crateApiExportTransactions(
  id: id,
  optionsJson: optionsJson,
);

Future<String> syncWallet({required String id}) =>
    RustLib.instance.api.crateApiSyncWallet(id: id);

/// Scans a wallet again from its first address with the current gap
/// limit, for funds an incremental sync can no longer see. Returns a
/// serialized `SyncReport`.
Future<String> rescanWallet({required String id}) =>
    RustLib.instance.api.crateApiRescanWallet(id: id);

/// Fetches an older round of history for a watched address. Returns how
/// many transactions were added; zero means the history is exhausted.
Future<String> loadMoreHistory({required String id}) =>
    RustLib.instance.api.crateApiLoadMoreHistory(id: id);

Future<String> syncAll({String? network}) =>
    RustLib.instance.api.crateApiSyncAll(network: network);

Future<String> getSettings() => RustLib.instance.api.crateApiGetSettings();

Future<String> setActiveNetwork({required String network}) =>
    RustLib.instance.api.crateApiSetActiveNetwork(network: network);

/// Sets the global gap limit applied to every descriptor wallet on the
/// next sync. Bounded to 1..=500 by the core.
Future<String> setGapLimit({required int gapLimit}) =>
    RustLib.instance.api.crateApiSetGapLimit(gapLimit: gapLimit);

/// Sets the backend for a network from a serialized `BackendConfig`.
Future<String> setBackend({
  required String network,
  required String configJson,
}) => RustLib.instance.api.crateApiSetBackend(
  network: network,
  configJson: configJson,
);

/// The public servers offered for a network, in settings order.
/// Returns a serialized `Vec<PublicServer>`, empty on regtest, which
/// has no public server by definition.
Future<String> publicServers({required String network}) =>
    RustLib.instance.api.crateApiPublicServers(network: network);

/// What an Electrum server's certificate amounts to right now, seen
/// through the handshake a sync would open. Returns a serialized
/// `CertificateReport`: the `host:port` an acceptance is recorded
/// against, plus the `status` the settings screen acts on.
Future<String> inspectCertificate({required String url}) =>
    RustLib.instance.api.crateApiInspectCertificate(url: url);

/// Remembers the certificate the user accepted for this server. That
/// host must present exactly this one from then on.
Future<String> trustCertificate({
  required String url,
  required String fingerprint,
}) => RustLib.instance.api.crateApiTrustCertificate(
  url: url,
  fingerprint: fingerprint,
);

/// Drops an accepted certificate, keyed by `host:port`: the next
/// connection to that host asks again.
Future<String> forgetCertificate({required String host}) =>
    RustLib.instance.api.crateApiForgetCertificate(host: host);

/// Stores one small app preference in the encrypted vault.
Future<String> setAppPref({required String key, required String value}) =>
    RustLib.instance.api.crateApiSetAppPref(key: key, value: value);

/// Decodes a transaction somebody else signed (PSBT as base64, hex or a
/// binary file passed as hex; raw transaction as hex; a `ur:crypto-psbt`
/// or BBQr envelope) and previews what it does on `network`. Returns a
/// serialized `TxPreview`; nothing is signed, nothing is sent.
Future<String> previewTransaction({
  required String input,
  required String network,
}) => RustLib.instance.api.crateApiPreviewTransaction(
  input: input,
  network: network,
);

/// Hands a fully signed transaction (hex) to the backend of `network`.
/// Returns a serialized `BroadcastReport`; a refusal comes back verbatim
/// as the error message.
Future<String> broadcastTransaction({
  required String network,
  required String hex,
}) => RustLib.instance.api.crateApiBroadcastTransaction(
  network: network,
  hex: hex,
);

/// Where a broadcast transaction (hex) stands as the backend of
/// `network` sees it. Returns a serialized `BroadcastStatus`.
Future<String> transactionStatus({
  required String network,
  required String hex,
}) =>
    RustLib.instance.api.crateApiTransactionStatus(network: network, hex: hex);

/// Where Tor stands for `.onion` backends. Returns a serialized
/// `TorStatus`: the mode, the route in use, and how far the built-in
/// client has bootstrapped.
Future<String> torStatus() => RustLib.instance.api.crateApiTorStatus();

/// Sets how `.onion` backends reach Tor from serialized `TorSettings`
/// (`mode`: auto, system, embedded; `socks_proxy`: `host:port` or null).
Future<String> setTorSettings({required String settingsJson}) =>
    RustLib.instance.api.crateApiSetTorSettings(settingsJson: settingsJson);

/// Resolves the route now, bootstrapping the built-in client if that is
/// the path. Up to a minute and a half on a first run. Returns a
/// serialized `TorRoute`.
Future<String> torConnect() => RustLib.instance.api.crateApiTorConnect();

/// The lock in place without its hash, serialized, or `null`.
Future<String> appLock() => RustLib.instance.api.crateApiAppLock();

/// Sets a lock (`kind` is `pin` or `password`), or replaces its secret;
/// replacing needs the current one.
Future<String> setAppLock({
  required String kind,
  required String secret,
  String? current,
}) => RustLib.instance.api.crateApiSetAppLock(
  kind: kind,
  secret: secret,
  current: current,
);

Future<String> clearAppLock({required String current}) =>
    RustLib.instance.api.crateApiClearAppLock(current: current);

/// Tries a secret. Returns a serialized `LockVerdict`, whose delay says
/// when the next attempt is looked at after repeated failures.
Future<String> verifyAppLock({required String secret}) =>
    RustLib.instance.api.crateApiVerifyAppLock(secret: secret);

/// Whether the phone's biometric prompt may stand in for the secret.
Future<String> setBiometricUnlock({
  required bool enabled,
  required String current,
}) => RustLib.instance.api.crateApiSetBiometricUnlock(
  enabled: enabled,
  current: current,
);

/// Seals the chosen wallets under a password from serialized
/// `BackupOptions`. Returns a serialized `BackupBundle`: base64 for a
/// file, UR frames for an animated QR.
Future<String> exportBackup({
  required String optionsJson,
  required String password,
}) => RustLib.instance.api.crateApiExportBackup(
  optionsJson: optionsJson,
  password: password,
);

/// Opens a backup (base64 of the file, or the `gerfaut-backup:` text a
/// scan yields) and lists what it holds. Returns a `BackupPreview`.
Future<String> previewBackup({
  required String source,
  required String password,
}) => RustLib.instance.api.crateApiPreviewBackup(
  source: source,
  password: password,
);

/// Restores the chosen wallets from serialized `ImportChoices`. Returns
/// a serialized `ImportReport`.
Future<String> importBackup({
  required String source,
  required String password,
  required String choicesJson,
}) => RustLib.instance.api.crateApiImportBackup(
  source: source,
  password: password,
  choicesJson: choicesJson,
);

/// Starts the live watch of the active network and hands everything it
/// says to this one caller, each a serialized `LiveEvent`, then
/// `{"type":"stopped"}` once the watch has ended. The caller announces
/// every transaction it gets: the core hands each one out once, and has
/// already taken it off its record.
///
/// One caller at a time: with a watch already held, the stream carries
/// a `{"error":{"kind":"live_running"}}` payload and ends. A caller
/// that goes away without [`live_stop`] stops the watch at the next
/// event, so nothing more is taken for nobody; the event in hand then
/// is lost with it, which is why the host stops the watch first.
Stream<String> liveRun() => RustLib.instance.api.crateApiLiveRun();

/// Stops the live watch and closes its connection. Returns at once; the
/// stream of [`live_run`] ends right after what the watch still held.
/// Idempotent.
Future<String> liveStop() => RustLib.instance.api.crateApiLiveStop();

/// Checks the connection now: the call an alarm makes every few
/// minutes, and a change of network makes at once, because the timers
/// of a sleeping phone do not run. Cheap, and nothing with no watch.
Future<String> liveTick() => RustLib.instance.api.crateApiLiveTick();

/// Where the watch stands. Returns a serialized `WatchStatus`, whose
/// state is `off` when none runs.
Future<String> liveStatus() => RustLib.instance.api.crateApiLiveStatus();

/// Subscribes this isolate to what the running watch says for the
/// screens (its status, the wallets it synced, blocks), each a
/// serialized `LiveEvent`, plus
/// `{"type":"stopped"}` when the watch ends. Returns once the listener
/// is gone. A listener that lags loses the oldest events, never the
/// watch, and never a transaction to announce.
Stream<String> liveEvents() => RustLib.instance.api.crateApiLiveEvents();

/// What the syncs of one wallet found that nobody has announced yet,
/// taken off the record in the vault: call it after every sync this
/// app runs of that wallet, whatever the report lists, and announce
/// everything it returns, or drop it on purpose (notices off, the app
/// disguised). Nothing it returns is ever returned again, to this
/// caller or to the live watch. Returns a serialized `Vec<LiveTx>`.
Future<String> claimAnnouncements({required String walletId}) =>
    RustLib.instance.api.crateApiClaimAnnouncements(walletId: walletId);

/// Whether anything this app sends has to go through Tor.
Future<String> usesTor() => RustLib.instance.api.crateApiUsesTor();

/// Fetches the current BTC price. `source` is one of `coingecko`,
/// `kraken`, `mempool_space`; `currency` is one of the `FiatCurrency`
/// identifiers. The source must quote the currency: only CoinGecko
/// serves the ones past the first seven. Returns a `PriceQuote`.
///
/// Through the manager, so the request takes the route the syncs take:
/// with a .onion node on any network it goes through Tor, and with Tor
/// out of reach it does not go at all and comes back as `tor`.
Future<String> fetchPrice({required String source, required String currency}) =>
    RustLib.instance.api.crateApiFetchPrice(source: source, currency: currency);

/// Checks the latest published release against the running version.
/// Returns a serialized `UpdateCheck`.
///
/// Through the manager, so the request takes the route the syncs take:
/// with an onion backend it goes through Tor, and with Tor out of reach
/// it does not go at all and comes back as `tor`.
Future<String> checkUpdate({required String currentVersion}) =>
    RustLib.instance.api.crateApiCheckUpdate(currentVersion: currentVersion);
