// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core_error_json`, `core_error_kind`, `decode_key`, `error_json`, `manager`, `ok_json`, `parse_network_opt`, `parse_network`, `parse_variant`, `to_json`

/// Opens (or creates) the vault under `data_dir` with a 32-byte key given
/// as 64 hex characters. Idempotent: once initialized, later calls (hot
/// restarts) succeed without reopening.
Future<String> initManager({required String dataDir, required String keyHex}) =>
    RustLib.instance.api.crateApiInitManager(dataDir: dataDir, keyHex: keyHex);

/// Classifies pasted or scanned wallet material. Returns the serialized
/// `ParsedInput` to pass back to [`add_wallet`] after user confirmation.
Future<String> parseInput({required String input}) =>
    RustLib.instance.api.crateApiParseInput(input: input);

/// Adds a wallet from a `ParsedInput` JSON on an explicit network.
/// Returns the new wallet's metadata.
Future<String> addWallet({
  required String name,
  required String parsedJson,
  required String network,
}) => RustLib.instance.api.crateApiAddWallet(
  name: name,
  parsedJson: parsedJson,
  network: network,
);

/// Lists wallet metadata, optionally restricted to one network.
Future<String> listWallets({String? network}) =>
    RustLib.instance.api.crateApiListWallets(network: network);

Future<String> removeWallet({required String id}) =>
    RustLib.instance.api.crateApiRemoveWallet(id: id);

Future<String> renameWallet({required String id, required String name}) =>
    RustLib.instance.api.crateApiRenameWallet(id: id, name: name);

Future<String> walletSnapshot({required String id}) =>
    RustLib.instance.api.crateApiWalletSnapshot(id: id);

Future<String> txDetail({required String id, required String txid}) =>
    RustLib.instance.api.crateApiTxDetail(id: id, txid: txid);

Future<String> utxos({required String id}) =>
    RustLib.instance.api.crateApiUtxos(id: id);

/// The next unused receive address plus `lookahead` upcoming ones.
Future<String> receiveAddresses({required String id, required int lookahead}) =>
    RustLib.instance.api.crateApiReceiveAddresses(id: id, lookahead: lookahead);

/// Revealed addresses of a wallet, by keychain, with usage and balance.
/// Capped by the core: an audit view, not an infinite scroll.
Future<String> addressList({required String id}) =>
    RustLib.instance.api.crateApiAddressList(id: id);

/// Builds a CSV export of one wallet's transactions from serialized
/// `ExportOptions`. Returns `{"ok": ExportResult}`; nothing leaves the
/// device.
Future<String> exportTransactions({
  required String id,
  required String optionsJson,
}) => RustLib.instance.api.crateApiExportTransactions(
  id: id,
  optionsJson: optionsJson,
);

Future<String> syncWallet({required String id}) =>
    RustLib.instance.api.crateApiSyncWallet(id: id);

/// Fetches an older round of history for a watched address. Returns how
/// many transactions were added; zero means the history is exhausted.
Future<String> loadMoreHistory({required String id}) =>
    RustLib.instance.api.crateApiLoadMoreHistory(id: id);

Future<String> syncAll({String? network}) =>
    RustLib.instance.api.crateApiSyncAll(network: network);

Future<String> getSettings() => RustLib.instance.api.crateApiGetSettings();

Future<String> setActiveNetwork({required String network}) =>
    RustLib.instance.api.crateApiSetActiveNetwork(network: network);

/// Sets the global gap limit applied to every descriptor wallet on the
/// next sync. Bounded to 1..=500 by the core.
Future<String> setGapLimit({required int gapLimit}) =>
    RustLib.instance.api.crateApiSetGapLimit(gapLimit: gapLimit);

/// Sets the backend for a network from a serialized `BackendConfig`.
Future<String> setBackend({
  required String network,
  required String configJson,
}) => RustLib.instance.api.crateApiSetBackend(
  network: network,
  configJson: configJson,
);

/// Stores one small app preference in the encrypted vault.
Future<String> setAppPref({required String key, required String value}) =>
    RustLib.instance.api.crateApiSetAppPref(key: key, value: value);

/// Fetches the current BTC price. `source` is one of `coingecko`,
/// `kraken`, `mempool_space`; `currency` one of `eur`, `usd`, `gbp`,
/// `chf`. Returns a serialized `PriceQuote`.
Future<String> fetchPrice({required String source, required String currency}) =>
    RustLib.instance.api.crateApiFetchPrice(source: source, currency: currency);

/// Checks the latest published release against the running version.
/// Returns a serialized `UpdateCheck`.
Future<String> checkUpdate({required String currentVersion}) =>
    RustLib.instance.api.crateApiCheckUpdate(currentVersion: currentVersion);
