// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1043722216;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_gerfaut',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiAddWallet({
    required String name,
    required String parsedJson,
    required String network,
  });

  Future<String> crateApiAddressList({required String id});

  Future<String> crateApiAppLock();

  Future<String> crateApiAssembleQr({required String framesJson});

  Future<String> crateApiBroadcastTransaction({
    required String network,
    required String hex,
  });

  Future<String> crateApiCheckUpdate({required String currentVersion});

  Future<String> crateApiClaimAnnouncements({required String findingsJson});

  Future<String> crateApiClearAppLock({required String current});

  Future<String> crateApiExportBackup({
    required String optionsJson,
    required String password,
  });

  Future<String> crateApiExportTransactions({
    required String id,
    required String optionsJson,
  });

  Future<String> crateApiFetchPrice({
    required String source,
    required String currency,
  });

  Future<String> crateApiForgetCertificate({required String host});

  Future<String> crateApiGetSettings();

  Future<String> crateApiImportBackup({
    required String source,
    required String password,
    required String choicesJson,
  });

  Future<void> crateApiInitApp();

  Future<String> crateApiInitManager({
    required String dataDir,
    required String keyHex,
  });

  Future<String> crateApiInspectCertificate({required String url});

  Future<String> crateApiListWallets({String? network});

  Stream<String> crateApiLiveEvents();

  Future<String> crateApiLiveStart();

  Future<String> crateApiLiveStatus();

  Future<String> crateApiLiveStop();

  Future<String> crateApiLiveTick();

  Future<String> crateApiLoadMoreHistory({required String id});

  Future<String> crateApiParseBackend({required String input});

  Future<String> crateApiParseInput({required String input, String? script});

  Future<String> crateApiParseInputWithOptions({
    required String input,
    required String optionsJson,
  });

  Future<String> crateApiPremiumAccount();

  Future<String> crateApiPremiumAcknowledgeOffline({PlatformInt64? until});

  Future<String> crateApiPremiumActivate({required String key});

  Future<String> crateApiPremiumChannels();

  Future<String> crateApiPremiumConfirmChannel({
    required String id,
    required String code,
  });

  Future<String> crateApiPremiumCreateChannel({
    required String kind,
    String? target,
    String? secret,
  });

  Future<String> crateApiPremiumDeleteAccount();

  Future<String> crateApiPremiumDeleteChannel({required String id});

  Future<String> crateApiPremiumForgetKey();

  Future<String> crateApiPremiumHeartbeat();

  Future<String> crateApiPremiumRecentEvents();

  Future<String> crateApiPremiumRefreshLicence();

  Future<String> crateApiPremiumState();

  Future<String> crateApiPremiumTestChannel({required String id});

  Future<String> crateApiPremiumUnwatchWallet({required String id});

  Future<String> crateApiPremiumWallets();

  Future<String> crateApiPremiumWatchWallet({required String id});

  Future<String> crateApiPreviewBackup({
    required String source,
    required String password,
  });

  Future<String> crateApiPreviewTransaction({
    required String input,
    required String network,
  });

  Future<String> crateApiPublicServers({required String network});

  Future<String> crateApiReceiveAddresses({
    required String id,
    required int lookahead,
  });

  Future<String> crateApiRemoveWallet({required String id});

  Future<String> crateApiRenameWallet({
    required String id,
    required String name,
  });

  Future<String> crateApiReorderWallets({required List<String> ids});

  Future<String> crateApiRescanWallet({required String id});

  Future<String> crateApiSetActiveNetwork({required String network});

  Future<String> crateApiSetAppLock({
    required String kind,
    required String secret,
    String? current,
  });

  Future<String> crateApiSetAppPref({
    required String key,
    required String value,
  });

  Future<String> crateApiSetBackend({
    required String network,
    required String configJson,
  });

  Future<String> crateApiSetBiometricUnlock({
    required bool enabled,
    required String current,
  });

  Future<String> crateApiSetGapLimit({required int gapLimit});

  Future<String> crateApiSetTorSettings({required String settingsJson});

  Future<String> crateApiSetWalletIcon({
    required String id,
    required String icon,
  });

  Future<String> crateApiSyncAll({String? network});

  Future<String> crateApiSyncWallet({required String id});

  Future<String> crateApiTorConnect();

  Future<String> crateApiTorStatus();

  Future<String> crateApiTransactionStatus({
    required String network,
    required String hex,
  });

  Future<String> crateApiTrustCertificate({
    required String url,
    required String fingerprint,
  });

  Future<String> crateApiTxDetail({required String id, required String txid});

  Future<String> crateApiUsesTor();

  Future<String> crateApiUtxos({required String id});

  Future<String> crateApiVerifyAppLock({required String secret});

  Future<String> crateApiWalletPolicy({required String id});

  Future<String> crateApiWalletSnapshot({required String id});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiAddWallet({
    required String name,
    required String parsedJson,
    required String network,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(parsedJson, serializer);
          sse_encode_String(network, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAddWalletConstMeta,
        argValues: [name, parsedJson, network],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddWalletConstMeta => const TaskConstMeta(
    debugName: "add_wallet",
    argNames: ["name", "parsedJson", "network"],
  );

  @override
  Future<String> crateApiAddressList({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAddressListConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddressListConstMeta =>
      const TaskConstMeta(debugName: "address_list", argNames: ["id"]);

  @override
  Future<String> crateApiAppLock() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppLockConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppLockConstMeta =>
      const TaskConstMeta(debugName: "app_lock", argNames: []);

  @override
  Future<String> crateApiAssembleQr({required String framesJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(framesJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAssembleQrConstMeta,
        argValues: [framesJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssembleQrConstMeta =>
      const TaskConstMeta(debugName: "assemble_qr", argNames: ["framesJson"]);

  @override
  Future<String> crateApiBroadcastTransaction({
    required String network,
    required String hex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(network, serializer);
          sse_encode_String(hex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBroadcastTransactionConstMeta,
        argValues: [network, hex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBroadcastTransactionConstMeta =>
      const TaskConstMeta(
        debugName: "broadcast_transaction",
        argNames: ["network", "hex"],
      );

  @override
  Future<String> crateApiCheckUpdate({required String currentVersion}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(currentVersion, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCheckUpdateConstMeta,
        argValues: [currentVersion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCheckUpdateConstMeta => const TaskConstMeta(
    debugName: "check_update",
    argNames: ["currentVersion"],
  );

  @override
  Future<String> crateApiClaimAnnouncements({required String findingsJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(findingsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClaimAnnouncementsConstMeta,
        argValues: [findingsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClaimAnnouncementsConstMeta => const TaskConstMeta(
    debugName: "claim_announcements",
    argNames: ["findingsJson"],
  );

  @override
  Future<String> crateApiClearAppLock({required String current}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(current, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClearAppLockConstMeta,
        argValues: [current],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClearAppLockConstMeta =>
      const TaskConstMeta(debugName: "clear_app_lock", argNames: ["current"]);

  @override
  Future<String> crateApiExportBackup({
    required String optionsJson,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(optionsJson, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExportBackupConstMeta,
        argValues: [optionsJson, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportBackupConstMeta => const TaskConstMeta(
    debugName: "export_backup",
    argNames: ["optionsJson", "password"],
  );

  @override
  Future<String> crateApiExportTransactions({
    required String id,
    required String optionsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(optionsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExportTransactionsConstMeta,
        argValues: [id, optionsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportTransactionsConstMeta => const TaskConstMeta(
    debugName: "export_transactions",
    argNames: ["id", "optionsJson"],
  );

  @override
  Future<String> crateApiFetchPrice({
    required String source,
    required String currency,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          sse_encode_String(currency, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFetchPriceConstMeta,
        argValues: [source, currency],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFetchPriceConstMeta => const TaskConstMeta(
    debugName: "fetch_price",
    argNames: ["source", "currency"],
  );

  @override
  Future<String> crateApiForgetCertificate({required String host}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiForgetCertificateConstMeta,
        argValues: [host],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiForgetCertificateConstMeta =>
      const TaskConstMeta(debugName: "forget_certificate", argNames: ["host"]);

  @override
  Future<String> crateApiGetSettings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetSettingsConstMeta =>
      const TaskConstMeta(debugName: "get_settings", argNames: []);

  @override
  Future<String> crateApiImportBackup({
    required String source,
    required String password,
    required String choicesJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          sse_encode_String(password, serializer);
          sse_encode_String(choicesJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiImportBackupConstMeta,
        argValues: [source, password, choicesJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportBackupConstMeta => const TaskConstMeta(
    debugName: "import_backup",
    argNames: ["source", "password", "choicesJson"],
  );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiInitManager({
    required String dataDir,
    required String keyHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          sse_encode_String(keyHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitManagerConstMeta,
        argValues: [dataDir, keyHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitManagerConstMeta => const TaskConstMeta(
    debugName: "init_manager",
    argNames: ["dataDir", "keyHex"],
  );

  @override
  Future<String> crateApiInspectCertificate({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInspectCertificateConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectCertificateConstMeta =>
      const TaskConstMeta(debugName: "inspect_certificate", argNames: ["url"]);

  @override
  Future<String> crateApiListWallets({String? network}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(network, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiListWalletsConstMeta,
        argValues: [network],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListWalletsConstMeta =>
      const TaskConstMeta(debugName: "list_wallets", argNames: ["network"]);

  @override
  Stream<String> crateApiLiveEvents() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 19,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiLiveEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLiveEventsConstMeta =>
      const TaskConstMeta(debugName: "live_events", argNames: ["sink"]);

  @override
  Future<String> crateApiLiveStart() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLiveStartConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLiveStartConstMeta =>
      const TaskConstMeta(debugName: "live_start", argNames: []);

  @override
  Future<String> crateApiLiveStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLiveStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLiveStatusConstMeta =>
      const TaskConstMeta(debugName: "live_status", argNames: []);

  @override
  Future<String> crateApiLiveStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLiveStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLiveStopConstMeta =>
      const TaskConstMeta(debugName: "live_stop", argNames: []);

  @override
  Future<String> crateApiLiveTick() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLiveTickConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLiveTickConstMeta =>
      const TaskConstMeta(debugName: "live_tick", argNames: []);

  @override
  Future<String> crateApiLoadMoreHistory({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoadMoreHistoryConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoadMoreHistoryConstMeta =>
      const TaskConstMeta(debugName: "load_more_history", argNames: ["id"]);

  @override
  Future<String> crateApiParseBackend({required String input}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiParseBackendConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParseBackendConstMeta =>
      const TaskConstMeta(debugName: "parse_backend", argNames: ["input"]);

  @override
  Future<String> crateApiParseInput({required String input, String? script}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          sse_encode_opt_String(script, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiParseInputConstMeta,
        argValues: [input, script],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParseInputConstMeta => const TaskConstMeta(
    debugName: "parse_input",
    argNames: ["input", "script"],
  );

  @override
  Future<String> crateApiParseInputWithOptions({
    required String input,
    required String optionsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          sse_encode_String(optionsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiParseInputWithOptionsConstMeta,
        argValues: [input, optionsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParseInputWithOptionsConstMeta =>
      const TaskConstMeta(
        debugName: "parse_input_with_options",
        argNames: ["input", "optionsJson"],
      );

  @override
  Future<String> crateApiPremiumAccount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumAccountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumAccountConstMeta =>
      const TaskConstMeta(debugName: "premium_account", argNames: []);

  @override
  Future<String> crateApiPremiumAcknowledgeOffline({PlatformInt64? until}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_i_64(until, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumAcknowledgeOfflineConstMeta,
        argValues: [until],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumAcknowledgeOfflineConstMeta =>
      const TaskConstMeta(
        debugName: "premium_acknowledge_offline",
        argNames: ["until"],
      );

  @override
  Future<String> crateApiPremiumActivate({required String key}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumActivateConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumActivateConstMeta =>
      const TaskConstMeta(debugName: "premium_activate", argNames: ["key"]);

  @override
  Future<String> crateApiPremiumChannels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumChannelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumChannelsConstMeta =>
      const TaskConstMeta(debugName: "premium_channels", argNames: []);

  @override
  Future<String> crateApiPremiumConfirmChannel({
    required String id,
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumConfirmChannelConstMeta,
        argValues: [id, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumConfirmChannelConstMeta =>
      const TaskConstMeta(
        debugName: "premium_confirm_channel",
        argNames: ["id", "code"],
      );

  @override
  Future<String> crateApiPremiumCreateChannel({
    required String kind,
    String? target,
    String? secret,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(kind, serializer);
          sse_encode_opt_String(target, serializer);
          sse_encode_opt_String(secret, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumCreateChannelConstMeta,
        argValues: [kind, target, secret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumCreateChannelConstMeta =>
      const TaskConstMeta(
        debugName: "premium_create_channel",
        argNames: ["kind", "target", "secret"],
      );

  @override
  Future<String> crateApiPremiumDeleteAccount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumDeleteAccountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumDeleteAccountConstMeta =>
      const TaskConstMeta(debugName: "premium_delete_account", argNames: []);

  @override
  Future<String> crateApiPremiumDeleteChannel({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumDeleteChannelConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumDeleteChannelConstMeta =>
      const TaskConstMeta(
        debugName: "premium_delete_channel",
        argNames: ["id"],
      );

  @override
  Future<String> crateApiPremiumForgetKey() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumForgetKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumForgetKeyConstMeta =>
      const TaskConstMeta(debugName: "premium_forget_key", argNames: []);

  @override
  Future<String> crateApiPremiumHeartbeat() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumHeartbeatConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumHeartbeatConstMeta =>
      const TaskConstMeta(debugName: "premium_heartbeat", argNames: []);

  @override
  Future<String> crateApiPremiumRecentEvents() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumRecentEventsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumRecentEventsConstMeta =>
      const TaskConstMeta(debugName: "premium_recent_events", argNames: []);

  @override
  Future<String> crateApiPremiumRefreshLicence() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumRefreshLicenceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumRefreshLicenceConstMeta =>
      const TaskConstMeta(debugName: "premium_refresh_licence", argNames: []);

  @override
  Future<String> crateApiPremiumState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumStateConstMeta =>
      const TaskConstMeta(debugName: "premium_state", argNames: []);

  @override
  Future<String> crateApiPremiumTestChannel({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumTestChannelConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumTestChannelConstMeta =>
      const TaskConstMeta(debugName: "premium_test_channel", argNames: ["id"]);

  @override
  Future<String> crateApiPremiumUnwatchWallet({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumUnwatchWalletConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumUnwatchWalletConstMeta =>
      const TaskConstMeta(
        debugName: "premium_unwatch_wallet",
        argNames: ["id"],
      );

  @override
  Future<String> crateApiPremiumWallets() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 43,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumWalletsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumWalletsConstMeta =>
      const TaskConstMeta(debugName: "premium_wallets", argNames: []);

  @override
  Future<String> crateApiPremiumWatchWallet({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 44,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPremiumWatchWalletConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPremiumWatchWalletConstMeta =>
      const TaskConstMeta(debugName: "premium_watch_wallet", argNames: ["id"]);

  @override
  Future<String> crateApiPreviewBackup({
    required String source,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPreviewBackupConstMeta,
        argValues: [source, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPreviewBackupConstMeta => const TaskConstMeta(
    debugName: "preview_backup",
    argNames: ["source", "password"],
  );

  @override
  Future<String> crateApiPreviewTransaction({
    required String input,
    required String network,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          sse_encode_String(network, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 46,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPreviewTransactionConstMeta,
        argValues: [input, network],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPreviewTransactionConstMeta => const TaskConstMeta(
    debugName: "preview_transaction",
    argNames: ["input", "network"],
  );

  @override
  Future<String> crateApiPublicServers({required String network}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(network, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 47,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPublicServersConstMeta,
        argValues: [network],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPublicServersConstMeta =>
      const TaskConstMeta(debugName: "public_servers", argNames: ["network"]);

  @override
  Future<String> crateApiReceiveAddresses({
    required String id,
    required int lookahead,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_u_32(lookahead, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 48,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReceiveAddressesConstMeta,
        argValues: [id, lookahead],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiveAddressesConstMeta => const TaskConstMeta(
    debugName: "receive_addresses",
    argNames: ["id", "lookahead"],
  );

  @override
  Future<String> crateApiRemoveWallet({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 49,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRemoveWalletConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoveWalletConstMeta =>
      const TaskConstMeta(debugName: "remove_wallet", argNames: ["id"]);

  @override
  Future<String> crateApiRenameWallet({
    required String id,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 50,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRenameWalletConstMeta,
        argValues: [id, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRenameWalletConstMeta =>
      const TaskConstMeta(debugName: "rename_wallet", argNames: ["id", "name"]);

  @override
  Future<String> crateApiReorderWallets({required List<String> ids}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(ids, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 51,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReorderWalletsConstMeta,
        argValues: [ids],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReorderWalletsConstMeta =>
      const TaskConstMeta(debugName: "reorder_wallets", argNames: ["ids"]);

  @override
  Future<String> crateApiRescanWallet({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 52,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRescanWalletConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRescanWalletConstMeta =>
      const TaskConstMeta(debugName: "rescan_wallet", argNames: ["id"]);

  @override
  Future<String> crateApiSetActiveNetwork({required String network}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(network, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 53,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetActiveNetworkConstMeta,
        argValues: [network],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetActiveNetworkConstMeta => const TaskConstMeta(
    debugName: "set_active_network",
    argNames: ["network"],
  );

  @override
  Future<String> crateApiSetAppLock({
    required String kind,
    required String secret,
    String? current,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(kind, serializer);
          sse_encode_String(secret, serializer);
          sse_encode_opt_String(current, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 54,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetAppLockConstMeta,
        argValues: [kind, secret, current],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetAppLockConstMeta => const TaskConstMeta(
    debugName: "set_app_lock",
    argNames: ["kind", "secret", "current"],
  );

  @override
  Future<String> crateApiSetAppPref({
    required String key,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 55,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetAppPrefConstMeta,
        argValues: [key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetAppPrefConstMeta => const TaskConstMeta(
    debugName: "set_app_pref",
    argNames: ["key", "value"],
  );

  @override
  Future<String> crateApiSetBackend({
    required String network,
    required String configJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(network, serializer);
          sse_encode_String(configJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 56,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetBackendConstMeta,
        argValues: [network, configJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetBackendConstMeta => const TaskConstMeta(
    debugName: "set_backend",
    argNames: ["network", "configJson"],
  );

  @override
  Future<String> crateApiSetBiometricUnlock({
    required bool enabled,
    required String current,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          sse_encode_String(current, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 57,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetBiometricUnlockConstMeta,
        argValues: [enabled, current],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetBiometricUnlockConstMeta => const TaskConstMeta(
    debugName: "set_biometric_unlock",
    argNames: ["enabled", "current"],
  );

  @override
  Future<String> crateApiSetGapLimit({required int gapLimit}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(gapLimit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 58,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetGapLimitConstMeta,
        argValues: [gapLimit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetGapLimitConstMeta =>
      const TaskConstMeta(debugName: "set_gap_limit", argNames: ["gapLimit"]);

  @override
  Future<String> crateApiSetTorSettings({required String settingsJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(settingsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 59,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetTorSettingsConstMeta,
        argValues: [settingsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetTorSettingsConstMeta => const TaskConstMeta(
    debugName: "set_tor_settings",
    argNames: ["settingsJson"],
  );

  @override
  Future<String> crateApiSetWalletIcon({
    required String id,
    required String icon,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(icon, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 60,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetWalletIconConstMeta,
        argValues: [id, icon],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetWalletIconConstMeta => const TaskConstMeta(
    debugName: "set_wallet_icon",
    argNames: ["id", "icon"],
  );

  @override
  Future<String> crateApiSyncAll({String? network}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(network, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 61,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSyncAllConstMeta,
        argValues: [network],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncAllConstMeta =>
      const TaskConstMeta(debugName: "sync_all", argNames: ["network"]);

  @override
  Future<String> crateApiSyncWallet({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 62,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSyncWalletConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWalletConstMeta =>
      const TaskConstMeta(debugName: "sync_wallet", argNames: ["id"]);

  @override
  Future<String> crateApiTorConnect() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 63,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTorConnectConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorConnectConstMeta =>
      const TaskConstMeta(debugName: "tor_connect", argNames: []);

  @override
  Future<String> crateApiTorStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 64,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTorStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorStatusConstMeta =>
      const TaskConstMeta(debugName: "tor_status", argNames: []);

  @override
  Future<String> crateApiTransactionStatus({
    required String network,
    required String hex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(network, serializer);
          sse_encode_String(hex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 65,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransactionStatusConstMeta,
        argValues: [network, hex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransactionStatusConstMeta => const TaskConstMeta(
    debugName: "transaction_status",
    argNames: ["network", "hex"],
  );

  @override
  Future<String> crateApiTrustCertificate({
    required String url,
    required String fingerprint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(fingerprint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 66,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTrustCertificateConstMeta,
        argValues: [url, fingerprint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTrustCertificateConstMeta => const TaskConstMeta(
    debugName: "trust_certificate",
    argNames: ["url", "fingerprint"],
  );

  @override
  Future<String> crateApiTxDetail({required String id, required String txid}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(txid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 67,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTxDetailConstMeta,
        argValues: [id, txid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxDetailConstMeta =>
      const TaskConstMeta(debugName: "tx_detail", argNames: ["id", "txid"]);

  @override
  Future<String> crateApiUsesTor() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 68,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUsesTorConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUsesTorConstMeta =>
      const TaskConstMeta(debugName: "uses_tor", argNames: []);

  @override
  Future<String> crateApiUtxos({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 69,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUtxosConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUtxosConstMeta =>
      const TaskConstMeta(debugName: "utxos", argNames: ["id"]);

  @override
  Future<String> crateApiVerifyAppLock({required String secret}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(secret, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 70,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVerifyAppLockConstMeta,
        argValues: [secret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVerifyAppLockConstMeta =>
      const TaskConstMeta(debugName: "verify_app_lock", argNames: ["secret"]);

  @override
  Future<String> crateApiWalletPolicy({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 71,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWalletPolicyConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletPolicyConstMeta =>
      const TaskConstMeta(debugName: "wallet_policy", argNames: ["id"]);

  @override
  Future<String> crateApiWalletSnapshot({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 72,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWalletSnapshotConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletSnapshotConstMeta =>
      const TaskConstMeta(debugName: "wallet_snapshot", argNames: ["id"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
